#include <iostream>
#include<iomanip> //BIBLIOTECA DO 'setprecision'

using namespace std;

int main(){

	short int CODIGO[2]; 		//REPRESENTA O CÓDIGO DA PEÇA
	short int QUANTIDADE[2];	//REPRESENTA A QUANTIDADE DE PEÇAS
	double PRECO[2]; 			//REPRESENTA O VALOR UNITÁRIO DE CADA PEÇA

	cin >> CODIGO[0] >> QUANTIDADE[0] >> PRECO[0]; //ATRIBUINDO VALORES PARA AS VARIÁVEIS DECLARADAS	[ETAPA 1]
	cin >> CODIGO[1] >> QUANTIDADE[1] >> PRECO[1]; //ATRIBUINDO VALORES PARA AS VARIÁVEIS DECLARADAS	[ETAPA 2]

	cout << "VALOR A PAGAR: R$ " << fixed << setprecision(2) << QUANTIDADE[0]*PRECO[0]+QUANTIDADE[1]*PRECO[1] << endl; //IMPRIMINDO EM TELA O VALOR TOTAL DA COMPRA DAS PEÇAS COM BASE NO SEU VALOR E SUA QUANTIDADE

	return 0;
}

//EXERCÍCIO DO 'URI - ONLINE JUDGE', PROBLEMA NÚMERO: 1010